export const steps=['C','D','E','F','G','A','B'];
const pcs=[0,2,4,5,7,9,11];
export const modes={major:[0,2,4,5,7,9,11],minor:[0,2,3,5,7,8,10],dorian:[0,2,3,5,7,9,10],mixolydian:[0,2,4,5,7,9,10]};
export const keyNames=['C','G','D','A','E','B','F#','C#','F','Bb','Eb','Ab','Db','Gb','Cb'];
export const fifthValues=[0,1,2,3,4,5,6,7,-1,-2,-3,-4,-5,-6,-7];
export const txt=(el,tag,fallback='')=>el?.getElementsByTagName(tag)[0]?.textContent??fallback;
export const direct=(el,tag)=>Array.from(el?.children??[]).filter(n=>n.tagName===tag);
export function parse(xml){if(xml.length>15e6)throw Error('This score is too large. Import a smaller selection.');const d=new DOMParser().parseFromString(xml,'application/xml');if(d.getElementsByTagName('parsererror').length||d.documentElement.tagName!=='score-partwise')throw Error('Please import a valid partwise MusicXML score (.musicxml, .xml, or .mxl).');if(!d.getElementsByTagName('note').length)throw Error('No notes were found in this score.');return d;}
export const serialize=d=>new XMLSerializer().serializeToString(d);
export const parts=d=>direct(d.documentElement,'part').map(p=>({id:p.id,name:txt(Array.from(d.getElementsByTagName('score-part')).find(s=>s.id===p.id),'part-name',p.id)}));
export function elem(d,tag,text){const e=d.createElement(tag);if(text!==undefined)e.textContent=String(text);return e;}
export function set(el,tag,text){let e=direct(el,tag)[0];if(!e){e=elem(el.ownerDocument,tag);el.appendChild(e);}e.textContent=String(text);return e;}
export function midi(n){const p=direct(n,'pitch')[0];return p?12*(Number(txt(p,'octave'))+1)+pcs[steps.indexOf(txt(p,'step'))]+Number(txt(p,'alter',0)):null;}
export function pitch(m,flats=false){const names=flats?['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B']:['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];const name=names[((m%12)+12)%12];return {step:name[0],alter:name.length>1?(flats?-1:1):0,octave:Math.floor(m/12)-1};}
export function writePitch(n,p){direct(n,'rest').forEach(e=>e.remove());let pe=direct(n,'pitch')[0];if(!pe){pe=elem(n.ownerDocument,'pitch');const chord=direct(n,'chord')[0];n.insertBefore(pe,chord?chord.nextSibling:n.firstChild);}pe.replaceChildren(elem(n.ownerDocument,'step',p.step));if(p.alter)pe.appendChild(elem(n.ownerDocument,'alter',p.alter));pe.appendChild(elem(n.ownerDocument,'octave',p.octave));direct(n,'accidental').forEach(e=>e.remove());}
export const noteName=n=>{const m=midi(n);if(m===null)return 'Rest';const p=direct(n,'pitch')[0];const a=Number(txt(p,'alter',0));return txt(p,'step')+(a===1?'♯':a===-1?'♭':a===2?'𝄪':a===-2?'𝄫':'')+txt(p,'octave');};
export function metadata(doc,id){const p=direct(doc.documentElement,'part').find(p=>p.id===id)||direct(doc.documentElement,'part')[0];return {title:txt(doc,'work-title',txt(doc,'movement-title','Untitled tune')),fifths:Number(txt(p,'fifths',0)),mode:txt(p,'mode','major'),beats:Number(txt(p,'beats',4)),beatType:Number(txt(p,'beat-type',4)),clef:txt(p,'sign','G')==='C'?'alto':'treble'};}
export function measures(doc,id){const p=direct(doc.documentElement,'part').find(p=>p.id===id);let divisions=1,beats=4,beatType=4,fifths=0;return direct(p,'measure').map((m,i)=>{const attrs=direct(m,'attributes')[0];divisions=Number(txt(attrs,'divisions',divisions));beats=Number(txt(attrs,'beats',beats));beatType=Number(txt(attrs,'beat-type',beatType));fifths=Number(txt(attrs,'fifths',fifths));let at=0,last=0,end=0;const notes=[];for(const child of m.children){if(child.tagName==='backup')at-=Number(txt(child,'duration',0))/divisions;if(child.tagName==='forward')at+=Number(txt(child,'duration',0))/divisions;if(child.tagName==='note'){const grace=!!direct(child,'grace').length;const duration=Number(txt(child,'duration',0))/divisions;const chord=!!direct(child,'chord').length;const start=chord?last:at;notes.push({el:child,midi:midi(child),start,duration,grace,voice:txt(child,'voice','1')});if(!chord){last=at;at+=duration;}end=Math.max(end,start+duration);}}return {el:m,index:i,number:m.getAttribute('number')||String(i+1),notes,divisions,beats,beatType,fifths,duration:end||beats*4/beatType};});}
export function scaleFor(root,mode){const match=root.match(/^([A-G])([#b]?)$/);const pc=pcs[steps.indexOf(match?.[1]||'D')]+(match?.[2]==='#'?1:match?.[2]==='b'?-1:0);return (modes[mode]||modes.major).map(x=>(x+pc+12)%12);}
export function scaleSpell(m,root,mode){const sc=scaleFor(root,mode),i=sc.indexOf((m%12+12)%12);if(i<0)return pitch(m,root.includes('b'));const step=steps[(steps.indexOf(root[0])+i)%7],base=pcs[steps.indexOf(step)];let alter=((m%12)-base+12)%12;if(alter>6)alter-=12;return {step,alter,octave:(m-base-alter)/12-1};}
export function shiftedFifths(f,semi){let n=f+semi*7;while(n>6)n-=12;while(n< -5)n+=12;return n;}
export function transposePitch(p,semi,oldFifths,newFifths){if(!semi)return {step:txt(p,'step'),alter:Number(txt(p,'alter',0)),octave:Number(txt(p,'octave'))};const oldTonic=((oldFifths*4)%7+7)%7,newTonic=((newFifths*4)%7+7)%7;const ka=(f,step)=>f>0&&['F','C','G','D','A','E','B'].slice(0,f).includes(steps[step])?1:f<0&&['B','E','A','D','G','C','F'].slice(0,-f).includes(steps[step])?-1:0;const oldPc=pcs[oldTonic]+ka(oldFifths,oldTonic),newPc=pcs[newTonic]+ka(newFifths,newTonic);let diatonic=newTonic-oldTonic+7*Math.round((oldPc+semi-newPc)/12);const oldD=Number(txt(p,'octave'))*7+steps.indexOf(txt(p,'step'));const d=oldD+diatonic;const step=steps[((d%7)+7)%7],octave=Math.floor(d/7);const oldM=12*(Number(txt(p,'octave'))+1)+pcs[steps.indexOf(txt(p,'step'))]+Number(txt(p,'alter',0));return {step,octave,alter:oldM+semi-(12*(octave+1)+pcs[steps.indexOf(step)])};}
export function makeMelody(source,id,options){const doc=source.cloneNode(true),root=doc.documentElement;const part=direct(root,'part').find(p=>p.id===id);direct(root,'part').filter(p=>p!==part).forEach(p=>p.remove());const list=direct(root,'part-list')[0];for(const e of [...list.children])if(e.tagName!=='score-part'||e.id!==id)e.remove();const definition=direct(list,'score-part')[0];set(definition,'part-name',options.clef==='alto'?'Viola':'Fiddle');direct(part,'measure').forEach(m=>direct(m,'print').forEach(e=>e.remove()));let f=0;for(const m of direct(part,'measure')){let a=direct(m,'attributes')[0];if(a&&direct(a,'key')[0])f=Number(txt(a,'fifths',0));const nf=shiftedFifths(f,options.semitones);if(a){for(const key of direct(a,'key'))set(key,'fifths',nf);for(const clef of direct(a,'clef')){set(clef,'sign',options.clef==='alto'?'C':'G');set(clef,'line',options.clef==='alto'?3:2);direct(clef,'clef-octave-change').forEach(e=>e.remove());}direct(a,'transpose').forEach(e=>e.remove());}
for(const n of direct(m,'note')){const p=direct(n,'pitch')[0];if(p){const next=transposePitch(p,options.semitones,f,nf);next.octave+=options.octave;writePitch(n,next);}direct(n,'stem').forEach(e=>e.remove());}
for(const h of direct(m,'harmony')){for(const tag of ['root','bass']){const e=direct(h,tag)[0];if(e){const p=elem(doc,'pitch');p.append(elem(doc,'step',txt(e,tag+'-step')),elem(doc,'alter',txt(e,tag+'-alter',0)),elem(doc,'octave',4));const trans=transposePitch(p,options.semitones,f,nf);set(e,tag+'-step',trans.step);if(trans.alter||direct(e,tag+'-alter').length)set(e,tag+'-alter',trans.alter);}}}}
const first=direct(part,'measure')[0];let a=direct(first,'attributes')[0];if(!a){a=elem(doc,'attributes');first.prepend(a);}if(!direct(a,'clef').length){const c=elem(doc,'clef');c.append(elem(doc,'sign',options.clef==='alto'?'C':'G'),elem(doc,'line',options.clef==='alto'?3:2));a.append(c);}return doc;}
export function chordCandidates(measure,root,mode){const sc=scaleFor(root,mode);return sc.map((pc,i)=>{const triad=[pc,sc[(i+2)%7],sc[(i+4)%7]],third=(triad[1]-pc+12)%12,fifth=(triad[2]-pc+12)%12;const qual=fifth===6?'dim':third===3?'m':'';const p=scaleSpell(60+pc,root,mode);const name=p.step+(p.alter===1?'#':p.alter===-1?'b':'')+qual;let score=i===0?0.5:0;for(const n of measure.notes.filter(n=>n.midi!==null&&!n.grace)){const weight=n.duration*(n.start===0?1.7:1);score+=weight*(triad.includes(n.midi%12)?2:-1);}if(qual==='dim')score-=3;return {name,pc,triad,score};}).sort((a,b)=>b.score-a.score);}
export function parseChord(name){const m=name.trim().match(/^([A-G])([#b]?)(maj7|m7|m|dim|sus2|sus4|7|5)?$/);if(!m)return null;const pc=(pcs[steps.indexOf(m[1])]+(m[2]==='#'?1:m[2]==='b'?-1:0)+12)%12;const ints={m:[0,3,7],dim:[0,3,6],sus2:[0,2,7],sus4:[0,5,7],'7':[0,4,7,10],maj7:[0,4,7,11],m7:[0,3,7,10],'5':[0,7]}[m[3]]||[0,4,7];return {name,pc,triad:ints.map(i=>(i+pc)%12),kind:({m:'minor',dim:'diminished',sus2:'suspended-second',sus4:'suspended-fourth','7':'dominant',maj7:'major-seventh',m7:'minor-seventh','5':'power'})[m[3]]||'major',step:m[1],alter:m[2]==='#'?1:m[2]==='b'?-1:0};}
export function addChord(m,name){const c=parseChord(name);if(!c)return;const d=m.ownerDocument,h=elem(d,'harmony'),r=elem(d,'root');r.append(elem(d,'root-step',c.step));if(c.alter)r.append(elem(d,'root-alter',c.alter));h.append(r,elem(d,'kind',c.kind));m.insertBefore(h,direct(m,'note')[0]||null);}
function addPart(doc,id,name){const d=elem(doc,'score-part');d.id=id;d.append(elem(doc,'part-name',name));direct(doc.documentElement,'part-list')[0].append(d);const p=elem(doc,'part');p.id=id;doc.documentElement.append(p);return p;}
function noteXML(d,m,duration,divisions,root,mode){const n=elem(d,'note');if(m===null)n.append(elem(d,'rest'));else writePitch(n,scaleSpell(m,root,mode));n.append(elem(d,'duration',Math.round(duration*divisions)));const values=[[4,'whole'],[3,'half'],[2,'half'],[1.5,'quarter'],[1,'quarter'],[.75,'eighth'],[.5,'eighth'],[.25,'16th'],[.125,'32nd']];const found=values.find(([q])=>Math.abs(duration-q)<.001);if(found){n.append(elem(d,'type',found[1]));if([3,1.5,.75].includes(duration))n.append(elem(d,'dot'));}return n;}
export function arrange(melody,id,settings,chords){const d=melody.cloneNode(true),part=direct(d.documentElement,'part')[0],ms=measures(d,id);if(settings.chords)ms.forEach((m,i)=>{if(chords[i]){direct(m.el,'harmony').forEach(h=>h.remove());addChord(m.el,chords[i]);}});
if(settings.harmony!=='off'){const p=addPart(d,'VH','Viola harmony');ms.forEach(m=>{const copy=m.el.cloneNode(true);for(const n of [...copy.children])if(!['attributes','note','backup','forward','barline'].includes(n.tagName))n.remove();for(const a of direct(copy,'attributes'))for(const c of direct(a,'clef')){set(c,'sign','C');set(c,'line',3);}for(const n of direct(copy,'note')){const mm=midi(n);if(mm!==null){const sc=scaleFor(settings.root,settings.mode);let candidates=[];for(let q=mm-12;q<mm;q++)if(sc.includes((q%12+12)%12))candidates.push(q);let target=candidates[candidates.length-(settings.harmony==='sixths'?5:2)]??mm-4;while(target<48)target+=12;writePitch(n,scaleSpell(target,settings.root,settings.mode));}direct(n,'lyric').forEach(e=>e.remove());}p.append(copy);});}
if(settings.drone!=='off'){const p=addPart(d,'VD','Viola drone');ms.forEach((m,i)=>{const el=elem(d,'measure');el.setAttribute('number',m.number);let attrs=elem(d,'attributes');attrs.append(elem(d,'divisions',m.divisions));const time=elem(d,'time');time.append(elem(d,'beats',m.beats),elem(d,'beat-type',m.beatType));if(i===0||m.beats!==ms[i-1].beats||m.beatType!==ms[i-1].beatType)attrs.append(time);const key=elem(d,'key');key.append(elem(d,'fifths',m.fifths));if(i===0||m.fifths!==ms[i-1].fifths)attrs.insertBefore(key,direct(attrs,'time')[0]||null);const clef=elem(d,'clef');clef.append(elem(d,'sign','C'),elem(d,'line',3));if(i===0)attrs.append(clef);el.append(attrs);const tonic=scaleFor(settings.root,settings.mode)[0]+48;let remaining=m.duration;const chunks=[];while(remaining>.001){const q=[4,3,2,1.5,1,.75,.5,.25,.125].find(x=>x<=remaining+.001)??remaining;chunks.push(q);remaining-=q;}
chunks.forEach((q,j)=>{for(const [k,mm] of (settings.drone==='fifth'?[tonic,tonic+7]:[tonic]).entries()){const n=noteXML(d,mm,q,m.divisions,settings.root,settings.mode);if(k)n.prepend(elem(d,'chord'));if(chunks.length>1){if(j>0)n.appendChild(elem(d,'tie')).setAttribute('type','stop');if(j<chunks.length-1)n.appendChild(elem(d,'tie')).setAttribute('type','start');const no=elem(d,'notations');if(j>0)no.appendChild(elem(d,'tied')).setAttribute('type','stop');if(j<chunks.length-1)no.appendChild(elem(d,'tied')).setAttribute('type','start');n.append(no);}el.append(n);}});direct(m.el,'barline').forEach(b=>el.append(b.cloneNode(true)));p.append(el);});}return d;}
export function fromDraft(draft,{title='Scanned tune',fifths=0,beats=4,beatType=4,clef='treble'}={}){const d=new DOMParser().parseFromString('<score-partwise version="4.0"><work><work-title/></work><part-list><score-part id="P1"><part-name>Melody</part-name></score-part></part-list><part id="P1"/></score-partwise>','application/xml');set(d.getElementsByTagName('work')[0],'work-title',title);const part=direct(d.documentElement,'part')[0];draft.forEach((notes,i)=>{const m=elem(d,'measure');m.setAttribute('number',i+1);if(i===0){const a=elem(d,'attributes');a.append(elem(d,'divisions',480));const key=elem(d,'key');key.append(elem(d,'fifths',fifths));const time=elem(d,'time');time.append(elem(d,'beats',beats),elem(d,'beat-type',beatType));const c=elem(d,'clef');c.append(elem(d,'sign',clef==='alto'?'C':'G'),elem(d,'line',clef==='alto'?3:2));a.append(key,time,c);m.append(a);}for(const note of notes){const n=noteXML(d,note.midi,note.duration,480,'C','major');if(note.pitch)writePitch(n,note.pitch);m.append(n);}part.append(m);});return d;}
export function demo(){const phrases=[[74,78,81,78,76,74],[76,78,79,81,79,76],[74,78,81,83,81,78],[76,74,73,74,74,74],[81,83,81,78,81,78],[79,81,79,76,79,76],[78,79,81,83,81,78],[76,74,73,74,74,74]];const d=fromDraft(phrases.map(p=>p.map(m=>({midi:m-12,duration:.5}))),{title:'A little session tune',fifths:2,beats:6,beatType:8});d.getElementsByTagName('creator');return d;}
